server:
  port: 2138

spring:
  # 数据源
  datasource:
    username: root
    password: 12138
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anchor_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

# 日志配置
logging:
  level:
    root: info
    com.fatehole: debug
  file:
    path: ./logs
  logback:
    rollingpolicy:
      # 归档
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
      # 日志保存日期
      max-history: 30
      # 开启启动清除
      clean-history-on-start: true
      max-file-size: 10MB

# MyBatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    # 控制台打印mybatis-plus的LOGO
    banner: false

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro:
#  sessionManager:
#    sessionIdCookieEnabled: true
#    sessionIdUrlRewritingEnabled: false
#  unauthorizedUrl: /unauthorized
#  successUrl: /
#  loginUrl: /login
#  web:
#    enabled: true